services:
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: owntone
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./config/owntone:/etc/owntone
      - ./cache/owntone:/var/cache/owntone
      - ./music:/srv/media
      - ./pipes:/srv/pipes
    depends_on:
      - librespot
    restart: unless-stopped

  librespot:
    image: giof71/librespot:latest
    container_name: librespot
    network_mode: host
    environment:
      - BACKEND=pipe
      - DEVICE=/mnt/pipe/spotify
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=OwnTone Spotify
      - DEVICE_TYPE=speaker
      - ONEVENT_COMMAND=spotify-metadata.sh
    volumes:
      - ./pipes:/mnt/pipe
      - ./scripts/spotify-metadata.sh:/userscripts/spotify-metadata.sh
    restart: unless-stopped
  shairport-sync:
    image: mikebrady/shairport-sync:classic
    container_name: shairport-sync
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./pipes:/data
      - ./config/shairport/shairport-sync.conf:/etc/shairport-sync.conf:ro
  audio-gate:
    # Points to the specific subfolder containing the Dockerfile
    build:
      context: ./docker/audio-gate
      dockerfile: Dockerfile
    container_name: audio-to-fifo
    restart: always
    # Passes the ALSA hardware directly into the container
    devices:
      - /dev/snd:/dev/snd
    ulimits:
      nice: -5
    # Maps the FIFO pipe directory to the host machine
    volumes:
      - ./pipes:/srv/pipes
    user: "0:0"
