// Minimal Configuration File for Classic (AirPlay 1) Shairport Sync

general =
{
  name = "%H";
  device_type = "speaker";    // This controls the icon
  output_backend = "pipe";
};

sessioncontrol =
{
  wait_for_completion = "no";
  allow_session_interruption = "yes";
  session_timeout = 30;
};

// Redirecting raw audio to your exact path
pipe =
{
  name = "/data/airplay";
};

// Redirecting metadata variables to your exact path
metadata =
{
  enabled = "yes";
  include_cover_art = "yes";

  metadata_pipename = "/data/airplay.metadata";
  metadata_sockaddr = "";
  metadata_sockport = 0;
};

diagnostics =
{
  log_output_to = "stdout";
  statistics = "no";
  log_verbosity = 0;
};
