# OwnTone configuration file

general {
	uid = "owntone"
	db_path = "/var/cache/owntone/database.db"
	logfile = "/dev/stderr"
	loglevel = log
	trusted_networks = { "any" }
}

library {
	name = "OwnTone"
	port = 3689
	directories = { "/srv/media", "/srv/pipes" }
	pipe_autostart = true
    allow_modifying_stored_playlists = true
}

audio {
	type = "disabled"
}

airplay "JukeBox" {
    exclude = true
}
